services:
  immich-drop:
    build: .
    container_name: immich-drop
    restart: unless-stopped
    ports:
      - "8080:8080"

    environment:
      #immich drop server ip
      PUBLIC_BASE_URL: http://192.168.8.60:8080
      # Immich connection
      IMMICH_BASE_URL: http://192.168.8.60:2283/api
      IMMICH_API_KEY: n7lO2oRFVhMXqI10YL8nfelIC9lZ8ND8AxZqx1XHiA
      #Enable/Disable Public upload page to folder
      PUBLIC_UPLOAD_PAGE_ENABLED: false
      IMMICH_ALBUM_NAME: dead-drop


    volumes:
      - immich_drop_data:/data
    healthcheck:
      test: ["CMD-SHELL", "python - <<'PY'\nimport urllib.request,sys\ntry:\n  urllib.request.urlopen('http://localhost:8080/').read(); sys.exit(0)\nexcept Exception:\n  sys.exit(1)\nPY"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  immich_drop_data:
